### ISSUE TITLE
Jython standalone doesnt work

### ISSUE THREAD

**Issue by ipentest** [v1ll41n/H1ReportFinder#1]
Hi Team,

Thanks a lot for the wonderful work on this project.. I tried installing this extension, however I cant do so since I wont be able to install all the stuff in requirements.txt as I am using jython-standalone-2.7.0.jar (so no bin folder)... Can you advice please?

Thanks again and stay safe,
Kiran

**Comment by v1ll41n** [comment]
Hi Kiran,
you can still install the required python packages using python-pip
`pip install -r requirements.txt`
and then in burpsuite Extender options tab, set  "_Folder for loading modules_"
to your site-packages dir path (ex: `/Python27/Lib/site-packages`).
I will include this workaround in the README for now, and In the next update, I may use regex instead to avoid the hassle of installing additional packages.
Regards,

**Comment by v1ll41n** [comment]
Hi Kiran,
you can still install the required python packages using python-pip
`pip install -r requirements.txt`
and then in burpsuite Extender options tab, set  "_Folder for loading modules_"
to your site-packages dir path (ex: `/Python27/Lib/site-packages`).
Regards,
